import { notFound } from "next/navigation";
import { Arrow, ServiceCta, SiteFooter, SiteHeader } from "../../../service-components";
import { serviceBySlug, softwareServices } from "../../../service-data";
export function generateStaticParams(){return softwareServices.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const x=serviceBySlug(slug);return x?{title:`${x.title} | Arch Engineering Services`,description:x.summary}:{};}
export default async function SoftwareDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const x=serviceBySlug(slug);if(!x||x.category!=="software")notFound();const related=x.related.map(serviceBySlug).filter(Boolean).filter(r=>r!.slug!==x.slug).slice(0,3);const gallery=[x.image,...related.map(r=>r!.image)].slice(0,3);return <main><SiteHeader/>
 <section className="detail-hero software-detail picture-detail-hero" style={{backgroundImage:`url(${x.image})`}}><div><p className="section-label pale">{x.eyebrow}</p><h1>{x.title}</h1><p>{x.summary}</p><div className="actions"><a className="button primary" href="/contact">Plan your software build <Arrow/></a><a className="button glass" href="#deliverables">View deliverables</a></div></div></section>
 <section className="detail-outcome section"><p className="section-label">THE BUSINESS OUTCOME</p><h2>{x.outcome}</h2><p>The solution is scoped around the people who use it, the information they need, and the measurable result the business expects.</p></section>
 <section className="service-story section"><div className="service-story-picture"><img src={x.image} alt={`${x.title} example`}/><span>Arch Software Development</span></div><div><p className="section-label">SOLUTION OVERVIEW</p><h2>Software designed around the real workflow.</h2><p>{x.summary} Discovery begins with the users, current process, information flow, bottlenecks, and the business result that should improve.</p><p>We then shape the interface, data, integrations, permissions, and release plan into clear increments. Early reviews reduce uncertainty and keep the application focused on useful daily work instead of unnecessary features.</p><div className="story-highlights"><span>User-centered workflow</span><span>Reviewable development stages</span><span>Testing and documentation</span></div></div></section>
 <section className="detail-split section" id="deliverables"><div><p className="section-label">WHAT YOU RECEIVE</p><h2>A buildable path<br/>to working software.</h2></div><div className="check-grid">{x.deliverables.map(v=><span key={v}>✓ {v}</span>)}</div><div><p className="section-label">TECHNOLOGY OPTIONS</p><div className="tool-cloud">{x.tools.map(v=><span key={v}>{v}</span>)}</div></div><div><p className="section-label">COMMON USE CASES</p><div className="tool-cloud">{x.uses.map(v=><span key={v}>{v}</span>)}</div></div></section>
 <section className="detail-process section"><div className="section-top"><div><p className="section-label pale">DELIVERY WORKFLOW</p><h2>Visible progress from idea to launch.</h2></div></div><div className="six-steps">{x.workflow.map((v,i)=><article key={v}><span>{String(i+1).padStart(2,"0")}</span><h3>{v}</h3></article>)}</div></section>
 <section className="faq-section section"><div><p className="section-label">COMMON QUESTIONS</p><h2>Before we begin.</h2></div><div>{x.faqs.map(([q,a])=><details key={q}><summary>{q}<b>+</b></summary><p>{a}</p></details>)}</div></section>
 <section className="service-gallery section"><div className="section-top"><div><p className="section-label">SOLUTION VISUALS</p><h2>Related software capabilities.</h2></div><p>Representative imagery for application design, development, integration, and operational technology.</p></div><div>{gallery.map((image,i)=><figure key={image}><img src={image} alt={`${x.title} visual ${i+1}`}/></figure>)}</div></section>
 <section className="related section"><p className="section-label">RELATED SERVICES</p><div>{related.map(r=><a className="related-picture-card" key={r!.slug} href={`/services/software/${r!.slug}`}><img src={r!.image} alt=""/><span>{r!.title}</span><Arrow/></a>)}</div></section>
 <ServiceCta title={`Ready to plan ${x.title.toLowerCase()}?`} text="Tell us who will use the system, what happens today, and what a better result looks like. We’ll help turn it into a clear scope."/><SiteFooter/></main>}
