import type { Metadata } from "next";
import { Arrow, ServiceCta, SiteFooter, SiteHeader } from "../../service-components";
import { mechanicalServices } from "../../service-data";

export const metadata: Metadata = { title: "Mechanical CAD & Inventor Automation | Arch Engineering Services", description: "Mechanical design, CAD detailing, Autodesk Inventor, SolidWorks, AutoCAD, and iLogic automation services for manufacturers." };
const automation = ["Batch PDF, DXF, and DWG export", "Automated drawing creation", "iProperty and title-block updates", "BOM export and validation", "File naming and folder creation", "Configurable parts and assemblies", "Sheet-metal flat-pattern processing", "Engineering workflow utilities"];

export default function MechanicalPage(){return <main><SiteHeader />
  <section className="inner-hero mechanical-hero"><div className="inner-hero-shade"/><div className="inner-hero-content"><p className="section-label pale">MECHANICAL ENGINEERING & CAD</p><h1>Precise drawings.<br/><span>Smarter workflows.</span></h1><p>Mechanical design, CAD detailing, and Autodesk Inventor automation that help manufacturing teams release accurate work faster.</p><div className="actions"><a className="button primary" href="#capabilities">Explore capabilities <Arrow /></a><a className="button glass" href="/#contact">Discuss a project</a></div></div></section>
  <section className="inner-intro section"><div><p className="section-label">PRACTICAL ENGINEERING SUPPORT</p><h2>Additional capacity when your team needs it.</h2></div><p>Whether you have a drawing backlog, a new assembly, or a repetitive Inventor process, Arch Engineering Services provides focused technical support with clear deliverables and direct communication.</p></section>
  <section className="capability-section section" id="capabilities"><div className="section-top"><div><p className="section-label">CAD SERVICES</p><h2>From model to<br/>manufacturing package.</h2></div><p>Support can be scoped as a single deliverable, a defined project, or ongoing engineering capacity.</p></div><div className="capability-grid image-card-grid">{mechanicalServices.map((item,i)=><a href={`/services/mechanical/${item.slug}`} key={item.slug}><article><div className="service-card-image"><img src={item.image} alt={`${item.title} engineering service`}/><span>{String(i+1).padStart(2,"0")}</span></div><div className="service-card-copy"><h3>{item.title}</h3><p>{item.summary}</p><b>Explore service →</b></div></article></a>)}</div></section>
  <section className="automation-detail"><div className="automation-panel"><div className="automation-ring"><span>iLogic</span><i>PDF</i><i>DXF</i><i>DWG</i></div></div><div><p className="section-label pale">AUTODESK INVENTOR iLOGIC</p><h2>Automate the work that engineers repeat.</h2><p>Custom iLogic tools reduce routine CAD operations while enforcing your file, drawing, and property standards.</p><div className="feature-list">{automation.map(item=><span key={item}>✓ {item}</span>)}</div><a className="button white" href="/#contact">Request a workflow review <Arrow /></a></div></section>
  <section className="deliverables section"><div className="section-top"><div><p className="section-label">TYPICAL DELIVERABLES</p><h2>Files your team<br/>can build from.</h2></div></div><div className="deliverable-row"><span>Inventor IPT / IAM / IDW</span><span>AutoCAD DWG / DXF</span><span>SolidWorks Parts & Assemblies</span><span>PDF Drawing Packages</span><span>BOM / Excel Reports</span></div></section>
  <ServiceCta title="Need help with a mechanical or CAD project?" text="Share the project scope, sample files, and required deliverables. We’ll review the work and recommend a practical next step."/><SiteFooter />
</main>}
