import { Arrow, SiteFooter, SiteHeader } from "./service-components";
import { mechanicalServices, softwareServices } from "./service-data";

const process=[["Discovery","We learn your goals, current workflow, available files, users, constraints, and expected outcome."],["Requirements","We define scope, deliverables, assumptions, schedule, review points, and pricing approach."],["Design","We prepare the CAD strategy, system architecture, interface, or automation logic."],["Development","Models, drawings, automation rules, or software are built in reviewable increments."],["Testing","The work is checked against requirements and reviewed for practical use and quality."],["Delivery & Support","You receive organized files, documentation, handoff guidance, and agreed support."]];
const industries=[["Manufacturing","/industry-images/manufacturing.jpg"],["Automotive","/industry-images/automotive.jpg"],["Aerospace","/industry-images/aerospace.jpg"],["Construction","/industry-images/construction.jpg"],["Energy","/industry-images/energy.jpg"],["Healthcare","/industry-images/healthcare.jpg"],["E-Commerce","/industry-images/ecommerce.jpg"],["Finance & Operations","/industry-images/finance.jpg"]];
const tech=["AUTODESK INVENTOR","AUTOCAD","SOLIDWORKS","iLOGIC","PYTHON","C# / .NET","JAVASCRIPT","REACT / NEXT.JS","FIREBASE","APIs"];

function ServiceCards({type}:{type:"mechanical"|"software"}){const list=type==="mechanical"?mechanicalServices:softwareServices;return <div className="reference-service-grid">{list.map((item,i)=><a href={`/services/${type}/${item.slug}`} key={item.slug} className="reference-service-card"><div className="reference-card-image"><img src={item.image} alt={item.title}/><span>{String(i+1).padStart(2,"0")}</span></div><div className="reference-card-body"><small>{type==="mechanical"?"MECHANICAL":"SOFTWARE"}</small><h3>{item.title}</h3><p>{item.summary}</p><b>Learn more <Arrow/></b></div></a>)}</div>}

export default function Home(){return <main><SiteHeader/>
 <section className="reference-hero" id="home"><div className="reference-hero-bg"><img src="/reference-assets/hero-engineering.jpg" alt="Engineering workspace"/></div><div className="reference-hero-overlay"/><div className="reference-hero-copy"><div className="availability"><i/> St. Louis based · Supporting teams nationwide</div><p className="section-label pale">MECHANICAL ENGINEERING + SOFTWARE</p><h1>One partner.<br/><span>Two powerful disciplines.</span></h1><p>Mechanical CAD, Inventor iLogic automation, and custom software that help manufacturers and businesses work faster, more accurately, and with fewer manual steps.</p><div className="actions"><a className="button primary" href="/contact">Start your project <Arrow/></a><a className="button glass" href="#mechanical-home">Explore services</a></div><div className="reference-stats"><div><b>10+</b><span>Years Mechanical & CAD</span></div><div><b>8+</b><span>Years Software</span></div><div><b>20</b><span>Focused Services</span></div></div></div><div className="reference-hero-gallery"><figure><img src="/reference-assets/cad-workspace.jpg" alt="CAD engineering"/><figcaption>Mechanical CAD & drawings</figcaption></figure><figure><img src="/reference-assets/hero-software.jpg" alt="Software development"/><figcaption>Custom software development</figcaption></figure></div></section>

 <section className="reference-about section" id="about"><div><p className="section-label">ABOUT ARCH ENGINEERING SERVICES</p><h2>Engineering depth.<br/><span>Software advantage.</span></h2><p>Arch Engineering Services is a founder-led St. Louis technical services company supporting manufacturers, contractors, engineering teams, and growing businesses.</p><p>With 10 years of mechanical/CAD experience and 8 years in software development, Sridhar Kota brings both disciplines together to solve the immediate technical requirement and improve the process behind it.</p><div className="about-points"><span>✓ Direct technical communication</span><span>✓ Flexible project-based support</span><span>✓ Mechanical and software under one roof</span></div><a className="button dark-button" href="/about">More about Arch <Arrow/></a></div><figure><img src="/reference-assets/about-engineer.jpg" alt="Engineer reviewing technical work"/><figcaption>Founder-led delivery · St. Louis, Missouri</figcaption></figure></section>

 <section className="reference-services mechanical-home" id="mechanical-home"><div className="reference-service-intro"><div><p className="section-label">MECHANICAL ENGINEERING</p><h2>From concept to manufacturing-ready documentation.</h2><p>CAD design, detailed drawings, product development, plant support, and automation tailored to your standards and workflow.</p><a className="button primary" href="/services/mechanical">Mechanical overview <Arrow/></a></div><img src="/reference-assets/factory-overview.jpg" alt="Mechanical engineering and manufacturing"/></div><ServiceCards type="mechanical"/></section>

 <section className="reference-services software-home" id="software-home"><div className="reference-service-intro reverse"><div><p className="section-label pale">SOFTWARE DEVELOPMENT</p><h2>Purpose-built systems for customers, teams, and operations.</h2><p>Web, mobile, and desktop applications designed around your actual process—from first prototype through launch and support.</p><a className="button white" href="/services/software">Software overview <Arrow/></a></div><img src="/reference-assets/software-team.jpg" alt="Software development team"/></div><ServiceCards type="software"/></section>

 <section className="reference-why section"><div className="why-photo"><img src="/reference-assets/why-team.jpg" alt="Technical collaboration"/><div><b>Engineering + Technology</b><span>under one accountable partner</span></div></div><div><p className="section-label">WHY ARCH</p><h2>Practical expertise without unnecessary layers.</h2><div className="why-list"><article><span>01</span><div><h3>Cross-disciplinary experience</h3><p>Mechanical judgment and software capability create stronger solutions and reveal useful automation opportunities.</p></div></article><article><span>02</span><div><h3>Direct accountability</h3><p>Work directly with the technical leader responsible for understanding, building, and delivering the project.</p></div></article><article><span>03</span><div><h3>Flexible engagement</h3><p>Start with one drawing, a defined automation, a complete application, or ongoing technical capacity.</p></div></article><article><span>04</span><div><h3>Clear deliverables</h3><p>Scope, outputs, schedule, review points, and responsibilities are established before work begins.</p></div></article></div></div></section>

 <section className="reference-process section" id="process"><div className="section-top"><div><p className="section-label pale">OUR PROCESS</p><h2>Clear progress from first conversation to delivery.</h2></div><a className="button glass" href="/process">View full process <Arrow/></a></div><div>{process.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

 <section className="reference-industries section" id="industries"><div className="section-top"><div><p className="section-label">INDUSTRIES WE SUPPORT</p><h2>Technical solutions across physical and digital operations.</h2></div><a className="inline-link" href="/industries">Explore industries <Arrow/></a></div><div className="industry-picture-grid">{industries.map(([title,image])=><a href="/industries" key={title}><img src={image} alt={title}/><span>{title}</span></a>)}</div></section>

 <section className="reference-tech"><p>TOOLS & TECHNOLOGIES</p><div>{tech.map(x=><span key={x}>{x}</span>)}</div></section>

 <section className="reference-contact" id="contact"><div><p className="section-label pale">LET’S BUILD SOMETHING USEFUL</p><h2>Have a project in mind?</h2><p>Tell us what you need designed, automated, or built. We’ll help define the practical next step.</p><div className="contact-mini"><a href="tel:+13147063946"><small>PHONE</small><b>(314) 706-3946</b></a><a href="mailto:archengservices2022@gmail.com"><small>EMAIL</small><b>archengservices2022@gmail.com</b></a><address>315 Lemay Ferry Road, Suite 135<br/>St. Louis, MO 63125</address></div></div><div className="reference-contact-panel"><h3>Ready to discuss the scope?</h3><p>Use our project enquiry page to select a service and provide your timeline, budget range, and requirements.</p><a className="button white" href="/contact">Request a quote <Arrow/></a></div></section>
 <a className="back-to-top" href="#home" aria-label="Back to top">↑</a><SiteFooter/>
 </main>}
