export type Service = {slug:string;title:string;image:string;category:"mechanical"|"software";eyebrow:string;summary:string;outcome:string;deliverables:string[];tools:string[];workflow:string[];uses:string[];faqs:[string,string][];related:string[]};
const images:Record<string,string>={
 "3d-modelling-drafting":"/service-images/3d-modelling-drafting.jpg",
 "sheet-metal-design":"/service-images/sheet-metal-design.jpg",
 "new-product-development":"/service-images/new-product-development.jpg",
 "reverse-engineering":"/service-images/reverse-engineering.jpg",
 "digitization":"/service-images/digitization.jpg",
 "cad-automation":"/service-images/cad-automation.jpg",
 "plant-engineering":"/service-images/plant-engineering.jpg",
 "structural-engineering":"/service-images/structural-engineering.jpg",
 "bim-services":"/service-images/bim-services.jpg",
 "cad-ams":"/service-images/cad-ams.jpg",
 "mechanical-drawings":"/service-images/mechanical-drawings.jpg",
 "tolerance-gdt":"/service-images/tolerance-gdt.jpg",
 "web-applications":"/service-images/web-applications.jpg",
 "mobile-apps":"/service-images/mobile-apps.jpg",
 "custom-software":"/service-images/custom-software.jpg",
 "erp-crm":"/service-images/erp-crm.jpg",
 "ui-ux-design":"/service-images/ui-ux-design.jpg",
 "api-integration":"/service-images/api-integration.jpg",
 "cloud-solutions":"/service-images/cloud-solutions.jpg",
 "cybersecurity-qa":"/service-images/cybersecurity-qa.jpg"
};
const flowM=["Review requirements and source files","Confirm standards, formats, and scope","Develop the model or drawing package","Complete an internal technical review","Incorporate agreed revisions","Deliver organized files and documentation"];
const flowS=["Understand users and business goals","Map the current workflow and requirements","Prototype the core experience","Build in reviewable increments","Test, secure, and prepare launch","Deploy, document, and support"];
const m=(slug:string,title:string,summary:string,deliverables:string[],tools:string[],uses:string[]):Service=>({slug,title,image:images[slug],category:"mechanical",eyebrow:"MECHANICAL ENGINEERING",summary,outcome:"Move from incomplete, outdated, or repetitive engineering work to clear manufacturing-ready information.",deliverables,tools,workflow:flowM,uses,faqs:[["Can you work with our existing files?","Yes. Available native CAD, PDFs, scans, markups, and standards can be reviewed before scope is confirmed."],["Which file formats can you deliver?","Typical outputs include native CAD, STEP, DWG, DXF, PDF, and spreadsheet documentation, depending on the project."],["How is the work priced?","Mechanical support is generally estimated from scope and hours. Typical hourly work may fall near $50–$65, subject to final review."]],related:["cad-automation","mechanical-drawings","3d-modelling-drafting"]});
const s=(slug:string,title:string,summary:string,deliverables:string[],tools:string[],uses:string[]):Service=>({slug,title,image:images[slug],category:"software",eyebrow:"SOFTWARE DEVELOPMENT",summary,outcome:"Replace disconnected manual work with a focused, maintainable system shaped around real users.",deliverables,tools,workflow:flowS,uses,faqs:[["Can you improve an existing application?","Yes. We can first review its architecture, code, workflows, and highest-priority problems, then define a practical improvement scope."],["How long will development take?","Timing depends on users, integrations, features, and release requirements. A discovery conversation is used to establish a realistic plan."],["Who owns the finished work?","Ownership, source delivery, hosting, and ongoing support are defined clearly in the project agreement before development begins."]],related:["custom-software","web-applications","api-integration"]});

export const services:Service[]=[
 m("3d-modelling-drafting","3D Modelling & 2D Drafting","Parametric models and coordinated drawings for parts, assemblies, fabrication, and release.",["3D part and assembly models","Production and assembly drawings","Exploded views and details","PDF and native CAD packages"],["Autodesk Inventor","SolidWorks","AutoCAD","STEP · DWG · PDF"],["Manufacturing drawings","Equipment and fixtures","Legacy design updates"]),
 m("sheet-metal-design","Sheet Metal Design","Practical sheet-metal parts and assemblies prepared with fabrication requirements in mind.",["Folded part models","Flat patterns and DXF files","Bend information","Fabrication drawing packages"],["Inventor Sheet Metal","SolidWorks Sheet Metal","DXF","DWG · PDF"],["Enclosures","Guards and brackets","Fabricated assemblies"]),
 m("new-product-development","New Product Development","Structured CAD support from early concept through a production-ready design package.",["Concept models","Design iterations","Prototype documentation","Release drawings and BOM support"],["Inventor","SolidWorks","AutoCAD","STEP · PDF"],["Industrial products","Fixtures and equipment","Manufactured components"]),
 m("reverse-engineering","Reverse Engineering","Recreate editable design information from physical parts, scans, measurements, and legacy documentation.",["As-built CAD models","Recreated drawings","Reference geometry","Comparison and revision notes"],["Inventor","SolidWorks","AutoCAD","Scan and measurement inputs"],["Replacement parts","Obsolete components","Design modernization"]),
 m("digitization","Digitization (2D & 3D)","Convert paper, PDF, and legacy information into organized editable CAD deliverables.",["Redrawn DWG files","3D CAD conversion","Layer and title-block organization","Searchable PDF packages"],["AutoCAD","Inventor","SolidWorks","PDF · DWG · STEP"],["Drawing archives","Plant documentation","Legacy product files"]),
 m("cad-automation","CAD Automation","Custom Inventor iLogic rules and utilities that reduce repetitive CAD and document work.",["PDF/DXF/DWG batch export","Automated naming and folders","iProperty and title-block updates","BOM and configurable design tools"],["Autodesk Inventor iLogic","VB.NET concepts","Excel integration","PDF · DXF · DWG"],["Drawing release automation","Product configurators","Engineering workflow utilities"]),
 m("plant-engineering","Plant Engineering","CAD documentation support for equipment arrangements, facilities, and manufacturing layouts.",["Equipment layouts","General arrangements","Piping and utility documentation","As-built updates"],["AutoCAD","Inventor","DWG · PDF","Client standards"],["Manufacturing facilities","Equipment installation","Layout revisions"]),
 m("structural-engineering","Structural Engineering Support","Modeling and detailing support for structural and fabricated systems within an agreed engineering scope.",["Structural models","Fabrication details","Connection documentation","Drawing updates"],["AutoCAD","Inventor","SolidWorks","DWG · PDF"],["Steel fabrication","Equipment frames","Construction documentation"]),
 m("bim-services","BIM Services","Coordinated digital building information and drawing support for multidisciplinary project teams.",["Discipline models","Coordination views","Drawing sheets","Model and document updates"],["BIM workflows","AutoCAD","PDF · DWG","Client coordination standards"],["Construction coordination","Facility documentation","Model updates"]),
 m("cad-ams","CAD AMS Services","Ongoing CAD application, data, standards, and workflow support for engineering teams.",["CAD standards support","Template maintenance","Workflow troubleshooting","Documentation and utilities"],["Inventor","AutoCAD","SolidWorks","iLogic"],["Engineering departments","Drawing standards","Recurring CAD support"]),
 m("mechanical-drawings","Mechanical Drawings","Detailed part, assembly, and fabrication drawings made clear for purchasing, inspection, and production.",["Part and assembly drawings","Dimensions and notes","Material and finish callouts","Revision-controlled PDFs"],["AutoCAD","Inventor","SolidWorks","DWG · PDF"],["Machined parts","Weldments","Assemblies"]),
 m("tolerance-gdt","Tolerance & GD&T","Drawing definition and tolerance support that communicates design intent more clearly.",["Tolerance reviews","GD&T annotations","Datum schemes","Stack-up support"],["ASME Y14.5 principles","Inventor","SolidWorks","Drawing standards"],["Production drawings","Inspection planning","Critical interfaces"]),
 s("web-applications","Web Applications","Responsive applications and portals that connect customers, teams, information, and workflows.",["UX and workflow prototype","Responsive web application","Role-based access","Deployment and documentation"],["JavaScript","React / Next.js","Python APIs","Firebase"],["Customer portals","Operations dashboards","Scheduling and reporting"]),
 s("mobile-apps","Mobile Apps (iOS & Android)","Field-ready mobile experiences for forms, photos, tasks, inspections, and communication.",["Mobile UX prototype","Cross-platform application","API and notification integration","Release support"],["React Native options","JavaScript","Firebase","REST APIs"],["Field operations","Inspection workflows","Customer self-service"]),
 s("custom-software","Custom Software Development","Purpose-built web and desktop software designed around your operation rather than a generic template.",["Requirements and solution design","Working software increments","Testing and documentation","Launch and support plan"],["Python","C# / .NET","JavaScript","Firebase"],["Workflow automation","Internal business tools","Engineering utilities"]),
 s("erp-crm","ERP / CRM Solutions","Focused operational systems that organize customer, job, inventory, and service information.",["Process mapping","Configured or custom modules","Data migration plan","Training and support documentation"],["Web platforms","APIs","Relational data","Reporting"],["Manufacturing operations","Field service","Small-business management"]),
 s("ui-ux-design","UI/UX Design","Clear user journeys, interfaces, and prototypes for software people can understand and use.",["User flows","Wireframes","High-fidelity interface designs","Clickable prototype and design system"],["Figma workflows","Responsive design","Design systems","Accessibility principles"],["New product planning","Application redesign","Developer handoff"]),
 s("api-integration","API Integration","Reliable connections between applications, services, devices, and business data.",["Integration architecture","API implementation","Authentication and error handling","Technical documentation"],["REST APIs","Python","C#","Webhooks · JSON"],["Payment and messaging","ERP connections","CAD and document workflows"]),
 s("cloud-solutions","Cloud Solutions","Practical hosting, deployment, storage, and operational foundations for modern applications.",["Environment architecture","Automated deployment workflow","Monitoring plan","Backup and operational documentation"],["Cloud platforms","Firebase","CI/CD","Containers where appropriate"],["Web application hosting","Data services","Deployment modernization"]),
 s("cybersecurity-qa","Cybersecurity & QA","Quality and security practices integrated into application planning, development, and release.",["Test strategy","Automated and manual testing","Security review findings","Release-readiness report"],["Application testing","Code review","OWASP principles","Automated QA tools"],["Existing application review","Release validation","Regression prevention"]),
];
export const mechanicalServices=services.filter(x=>x.category==="mechanical");
export const softwareServices=services.filter(x=>x.category==="software");
export const serviceBySlug=(slug:string)=>services.find(x=>x.slug===slug);
