import type { Metadata } from "next";
import { Arrow, ServiceCta, SiteFooter, SiteHeader } from "../../service-components";
import { softwareServices } from "../../service-data";

export const metadata: Metadata = { title: "Custom Software Development | Arch Engineering Services", description: "Custom web, desktop, and mobile software for manufacturers, contractors, and growing businesses." };
const projects=[
  ["Field Operations Platform", "Customers, scheduling, estimates, invoices, crews, photos, and reporting in one connected workflow."],
  ["Engineering Document Automation", "Extract and organize drawing information, generate reports, and reduce repetitive document processing."],
  ["Employee Performance System", "Role-based reviews, weighted evaluation categories, manager workflows, and HR reporting."],
];

export default function SoftwarePage(){return <main><SiteHeader />
  <section className="inner-hero software-hero"><div className="inner-hero-shade software-shade"/><div className="inner-hero-content"><p className="section-label pale">CUSTOM SOFTWARE DEVELOPMENT</p><h1>Software shaped<br/><span>around your business.</span></h1><p>Web, desktop, and mobile applications that simplify operations, connect information, and support measurable business growth.</p><div className="actions"><a className="button primary" href="#solutions">Explore solutions <Arrow /></a><a className="button glass" href="#projects">See project types</a></div></div><div className="software-float"><div className="mini-window"><div/><span/><span/><span/></div><div className="mini-mobile"><i/><i/><i/></div></div></section>
  <section className="inner-intro section"><div><p className="section-label">FROM IDEA TO WORKING PRODUCT</p><h2>Technology that fits the way you operate.</h2></div><p>We begin with the business problem—not a predetermined platform. The result is a focused application with the right users, workflows, information, and integrations.</p></section>
  <section className="capability-section section" id="solutions"><div className="section-top"><div><p className="section-label">SOFTWARE SERVICES</p><h2>Built for customers,<br/>teams, and operations.</h2></div><p>Start with a prototype, launch a complete application, or improve an existing system.</p></div><div className="solution-grid image-card-grid">{softwareServices.map((item,i)=><a href={`/services/software/${item.slug}`} key={item.slug}><article><div className="service-card-image"><img src={item.image} alt={`${item.title} software service`}/><span>{String(i+1).padStart(2,"0")}</span></div><div className="service-card-copy"><h3>{item.title}</h3><p>{item.summary}</p><div className="card-tools">{item.tools.slice(0,3).map(tag=><small key={tag}>{tag}</small>)}</div><strong>Explore service →</strong></div></article></a>)}</div></section>
  <section className="projects-section section" id="projects"><div className="section-top"><div><p className="section-label pale">EXAMPLE SOLUTIONS</p><h2>Useful systems—not generic demos.</h2></div><p>These examples show the kinds of operational problems we can structure into practical software.</p></div><div className="project-stack">{projects.map(([title,text],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div><Arrow /></article>)}</div></section>
  <section className="software-process section"><div className="section-top"><div><p className="section-label">DELIVERY PROCESS</p><h2>Clear progress at<br/>every stage.</h2></div></div><div className="steps"><div><span>01</span><h3>Discover</h3><p>Users, business goals, current process, and success measures.</p></div><div><span>02</span><h3>Prototype</h3><p>Core screens and workflows for early feedback and alignment.</p></div><div><span>03</span><h3>Build & Test</h3><p>Incremental development, review, security, and quality checks.</p></div><div><span>04</span><h3>Launch & Support</h3><p>Deployment, training, documentation, and ongoing improvements.</p></div></div></section>
  <section className="tech-band"><span>PYTHON</span><span>C# / .NET</span><span>JAVASCRIPT</span><span>REACT / NEXT.JS</span><span>FIREBASE</span><span>APIs</span></section>
  <ServiceCta title="Have a software idea or broken workflow?" text="Describe the users, current process, and result you need. We’ll help turn it into a clear, buildable software scope."/><SiteFooter />
</main>}
