import { notFound } from "next/navigation";
import { Arrow, ServiceCta, SiteFooter, SiteHeader } from "../../../service-components";
import { mechanicalServices, serviceBySlug } from "../../../service-data";
export function generateStaticParams(){return mechanicalServices.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const x=serviceBySlug(slug);return x?{title:`${x.title} | Arch Engineering Services`,description:x.summary}:{};}
export default async function MechanicalDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const x=serviceBySlug(slug);if(!x||x.category!=="mechanical")notFound();const related=x.related.map(serviceBySlug).filter(Boolean).filter(r=>r!.slug!==x.slug).slice(0,3);const gallery=[x.image,...related.map(r=>r!.image)].slice(0,3);return <main><SiteHeader/>
 <section className="detail-hero mechanical-detail picture-detail-hero" style={{backgroundImage:`url(${x.image})`}}><div><p className="section-label pale">{x.eyebrow}</p><h1>{x.title}</h1><p>{x.summary}</p><div className="actions"><a className="button primary" href="/contact">Discuss your project <Arrow/></a><a className="button glass" href="#deliverables">View deliverables</a></div></div></section>
 <section className="detail-outcome section"><p className="section-label">THE PRACTICAL OUTCOME</p><h2>{x.outcome}</h2><p>Arch provides founder-led technical support with a defined scope, organized deliverables, and direct communication throughout the work.</p></section>
 <section className="service-story section"><div className="service-story-picture"><img src={x.image} alt={`${x.title} example`}/><span>Arch Engineering Services</span></div><div><p className="section-label">SERVICE OVERVIEW</p><h2>Engineering support shaped around your standards.</h2><p>{x.summary} We begin by reviewing the information you already have, the manufacturing or coordination purpose, and the files your downstream team needs.</p><p>The work is then organized around agreed standards, review points, revision expectations, and final formats. This keeps the engagement focused while producing information that purchasing, fabrication, inspection, installation, or engineering teams can use.</p><div className="story-highlights"><span>Defined scope and assumptions</span><span>Direct technical communication</span><span>Organized, editable deliverables</span></div></div></section>
 <section className="detail-split section" id="deliverables"><div><p className="section-label">WHAT YOU RECEIVE</p><h2>Useful deliverables,<br/>clearly organized.</h2></div><div className="check-grid">{x.deliverables.map(v=><span key={v}>✓ {v}</span>)}</div><div><p className="section-label">TOOLS & FORMATS</p><div className="tool-cloud">{x.tools.map(v=><span key={v}>{v}</span>)}</div></div><div><p className="section-label">COMMON APPLICATIONS</p><div className="tool-cloud">{x.uses.map(v=><span key={v}>{v}</span>)}</div></div></section>
 <section className="detail-process section"><div className="section-top"><div><p className="section-label pale">DELIVERY WORKFLOW</p><h2>Six clear steps from input to release.</h2></div></div><div className="six-steps">{x.workflow.map((v,i)=><article key={v}><span>{String(i+1).padStart(2,"0")}</span><h3>{v}</h3></article>)}</div></section>
 <section className="faq-section section"><div><p className="section-label">COMMON QUESTIONS</p><h2>Before we begin.</h2></div><div>{x.faqs.map(([q,a])=><details key={q}><summary>{q}<b>+</b></summary><p>{a}</p></details>)}</div></section>
 <section className="service-gallery section"><div className="section-top"><div><p className="section-label">SERVICE VISUALS</p><h2>Related engineering capabilities.</h2></div><p>Representative imagery showing the types of technical work and environments supported.</p></div><div>{gallery.map((image,i)=><figure key={image}><img src={image} alt={`${x.title} visual ${i+1}`}/></figure>)}</div></section>
 <section className="related section"><p className="section-label">RELATED SERVICES</p><div>{related.map(r=><a className="related-picture-card" key={r!.slug} href={`/services/mechanical/${r!.slug}`}><img src={r!.image} alt=""/><span>{r!.title}</span><Arrow/></a>)}</div></section>
 <ServiceCta title={`Ready to discuss ${x.title.toLowerCase()}?`} text="Send the available files, requirements, and desired delivery format. We’ll review the project and recommend a practical scope."/><SiteFooter/></main>}
